# Generated by Django 3.1.1 on 2021-03-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0002_auto_20210323_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='role',
            new_name='req_role',
        ),
        migrations.AddField(
            model_name='requests',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meteroEvents.events'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
