# Generated by Django 3.1.1 on 2021-03-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0004_auto_20210324_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='cancellation',
            new_name='isApproved',
        ),
    ]
