# Generated by Django 3.1.1 on 2021-03-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0005_auto_20210324_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteroEvents.organizers'),
        ),
    ]
