# Generated by Django 3.1.1 on 2021-03-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0006_auto_20210325_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteroEvents.users'),
        ),
    ]
