# Generated by Django 3.0.8 on 2021-03-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cancellation',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteroEvents.Organizers'),
        ),
        migrations.AlterField(
            model_name='requesttoadmin',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requesttoadmin',
            name='req_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='requesttoorg',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requesttoorg',
            name='req_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='requesttopart',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requesttopart',
            name='req_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(max_length=100),
        ),
    ]
