# Generated by Django 3.1.1 on 2021-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cancellation',
            field=models.BinaryField(default=0),
        ),
    ]
