# Generated by Django 3.1.1 on 2021-03-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0002_auto_20210320_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='user_id',
            new_name='participant_id',
        ),
        migrations.RemoveField(
            model_name='organizers',
            name='organizer_id',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='participants_id',
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.IntegerField()),
                ('role', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteroEvents.users')),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
    ]
