# Generated by Django 3.1.1 on 2021-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0002_auto_20210323_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='targetLocation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
