# Generated by Django 3.1.1 on 2021-03-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0003_auto_20210323_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='organizer',
        ),
    ]
