# Generated by Django 3.1.1 on 2021-03-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0003_auto_20210320_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='user_id',
            new_name='user',
        ),
    ]
