# Generated by Django 3.1.1 on 2021-03-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0004_remove_events_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cancellationDate',
            field=models.DateField(),
        ),
    ]
