# Generated by Django 3.1.1 on 2021-03-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0004_auto_20210320_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizers',
            name='registered_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='req_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
