# Generated by Django 3.1.1 on 2021-03-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0005_auto_20210323_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_id',
        ),
    ]
