# Generated by Django 3.1.1 on 2021-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0005_auto_20210321_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(default='Male', max_length=5),
        ),
    ]
