# Generated by Django 3.1.1 on 2021-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0006_remove_events_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
