# Generated by Django 3.1.1 on 2021-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0007_auto_20210325_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='isApproved',
            field=models.IntegerField(default=0),
        ),
    ]
