# Generated by Django 3.1.1 on 2021-03-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0007_auto_20210323_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cancellationDate',
            field=models.DateField(null=True),
        ),
    ]
