# Generated by Django 3.1.1 on 2021-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0007_auto_20210321_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.IntegerField(default=1, max_length=4),
        ),
    ]
