# Generated by Django 3.1.1 on 2021-03-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteroEvents', '0008_auto_20210323_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='meteroEvents.organizers'),
        ),
    ]
